# Generated by Django 4.0.3 on 2022-04-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oem_part_number', models.CharField(db_index=True, max_length=12)),
                ('brand', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('image', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=150, null=True)),
                ('diameter', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
