# Generated by Django 4.0.3 on 2022-05-10 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_brand_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.manufacturer'),
        ),
    ]
