# Generated by Django 4.0.3 on 2022-05-11 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_brand_new_product_category_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.manufacturer'),
        ),
    ]
