# Generated by Django 4.0.3 on 2022-05-11 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_manufacturer_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brand'),
        ),
    ]
