# Generated by Django 4.0.3 on 2022-05-11 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_category_new_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
    ]
