# Generated by Django 4.0.3 on 2022-05-18 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_orderitem_product_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.link'),
        ),
    ]
