# Generated by Django 4.0.3 on 2022-05-23 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_carmodelbyyear_carmodels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarModels',
            new_name='CarModel',
        ),
    ]
