# Generated by Django 4.0.3 on 2022-05-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_carmodel_created_at_alter_carmodel_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='oem_parts',
        ),
        migrations.AddField(
            model_name='oempart',
            name='car_model',
            field=models.ManyToManyField(to='core.carmodel'),
        ),
    ]
