# Generated by Django 4.0.3 on 2022-05-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_carmodel_oem_parts_oempart_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oem_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.oempart'),
        ),
    ]
