# Generated by Django 4.0.3 on 2022-05-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_product_oem_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='oem_part_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
